### ISSUE TITLE
Witness not being correctly padded when the composer is reused

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#198]
Issue also seen in #186 and not solved (apparently) in #188
We import the `PreProcessedCircuit` and the keys as:
```rust
lazy_static! {
    static ref PREPROCESSED_CIRCUIT: PreProcessedCircuit = {
        let ser_data = fs::read("examples/.prep_circ_2_3.bin")
            .expect("Missing PreProcessedCircuit serialized data.");
        let prep_circ: PreProcessedCircuit = bincode::deserialize(&ser_data).unwrap();
        println!("{:?}", prep_circ);
        prep_circ
    };
    static ref VERIFIER_KEY: VerifierKey = {
        let ser_pub_params = fs::read(&"public_params.bin")
            .expect("File not found. Run example `0_setup_srs.rs` first please");
        let pub_params: PublicParameters = bincode::deserialize(&ser_pub_params).unwrap();
        let verif_key: VerifierKey = pub_params.trim(CIRCUIT_SIZE.next_power_of_two()).unwrap().1;
        verif_key
    };
    static ref PROVER_KEY: ProverKey = {
        let ser_pub_params = fs::read(&"public_params.bin")
            .expect("File not found. Run example `0_setup_srs.rs` first please");
        let pub_params: PublicParameters = bincode::deserialize(&ser_pub_params).unwrap();
        let prov_key: ProverKey = pub_params
            .trim(2 * CIRCUIT_SIZE.next_power_of_two())
            .unwrap()
            .0;
        prov_key
    };
    static ref EVAL_DOMAIN: EvaluationDomain = {
        let eval = EvaluationDomain::new(CIRCUIT_SIZE).unwrap();
        eval
    };
```

Later one, we want to create a `Proof` that uses the same exact circuit.
To do so, we have the following code:
```rust
// Define constants we already know.
const CIRCUIT_SIZE: usize = 20usize;

fn gadget_builder(composer: &mut StandardComposer, inputs: &[Scalar], final_result: Scalar) {
    let a = composer.add_input(inputs[0]);
    let b = composer.add_input(inputs[1]);
    let c = composer.add_input(inputs[2]);
    let d = composer.add_input(inputs[3]);

    let a_plus_b = composer.add(
        (Scalar::one(), a),
        (Scalar::one(), b),
        Scalar::zero(),
        Scalar::zero(),
    );

    let c_plus_d = composer.big_add(
        (Scalar::one(), c),
        (Scalar::one(), d),
        (Scalar::zero(), composer.zero_var),
        Scalar::zero(),
        Scalar::zero(),
    );

    let ab_xor_cd = composer.logic_xor_gate(a_plus_b, c_plus_d, 14usize);
    composer.bool_gate(ab_xor_cd);
    composer.constrain_to_constant(ab_xor_cd, Scalar::zero(), final_result);
    composer.add_dummy_constraints();
}

fn elaborate_proof(composer: &mut StandardComposer, transcript: &mut Transcript) -> Proof {
    composer.prove(&PROVER_KEY, &PREPROCESSED_CIRCUIT, transcript)
}

fn verify_proof(proof: &Proof, pub_input: Scalar) -> bool {
    let mut verif_transcript = Transcript::new(b"Gadget-Orientation-Is-Cool");
    let zero = Scalar::zero();

    proof.verify(
        &PREPROCESSED_CIRCUIT,
        &mut verif_transcript,
        &VERIFIER_KEY,
        &[
            zero, zero, zero, zero, zero, zero, zero, zero, zero, zero, zero, zero, pub_input,
        ],
    )
}

fn start_proving(inputs: &[Scalar], final_result: Scalar) -> Proof {
    let mut composer = StandardComposer::new();
    let mut transcript = Transcript::new(b"Gadget-Orientation-Is-Cool");
    gadget_builder(&mut composer, inputs, final_result);
    elaborate_proof(&mut composer, &mut transcript)
}

fn main() {
    // The public input is PUBLIC so we assume that the `Provers` and `Verifiers`
    // already know it.
    let pub_input = -Scalar::one();

    // Let's suppose that the following inputs arrive through the network or another rust
    // process or function:
    let inputs = vec![
        Scalar::from(6u64),
        Scalar::from(4u64),
        Scalar::from(3u64),
        Scalar::from(8u64),
    ];
    // We just need to do call one function to build a proof
    let proof = start_proving(&inputs, pub_input);
    // Verify it is as easy as
    assert!(verify_proof(&proof, pub_input) == true);
}
```

It turns out that the `proving` stage fails with the following error:
```
thread 'main' panicked at 'assertion failed: index < len', src/liballoc/vec.rs:1035:9

** This is the important part of the stack trace:
  16: plonk::permutation::permutation::Permutation::compute_fast_permutation_poly
             at src/permutation/permutation.rs:592
  17: plonk::permutation::permutation::Permutation::compute_permutation_poly
             at src/permutation/permutation.rs:197
```

As far as I've been able to dig into the problem, the problem is on this call:
`z.remove(n);` inside of the function: `compute_fast_permutation_poly()`.

For our specific case, the length of `z` is 21 and `n` is 32. That's why `remove` panics.
According to @kevaundray code comments, we should be expecting a `z` with `n+1` terms, but this is not what is indeed happening since `z.len() = 21`.

It seems that the padding has not been applied somewhere. Since the next power of two regarding 21 will be 32 and then everything will work as expected. 

**Note that our circuit size is 20 and we are getting a `z.len() = 21` so it will work correctly if no padding was applied.

**Comment by CPerezz** [comment]
The thing that seems to be the most logical is to change the `CIRCUIT_SIZE` constant of the example to be the next power of two regarding the circuit size that we already know.

After doing it, the length of `z` is is still equal to 21.

So looks to me that it is independent of the circuit_size that we define. It's just related to the padding that is not being applied.

**Comment by CPerezz** [comment]
As I thought, we haven't padded the `witness polynomials`.

This means that when we compute: 
```rust
 // Compute left_wire + gamma
        let w_l_gamma: Vec<_> = w_l.par_iter().map(|w_l| w_l + gamma).collect();
        // Compute right_wire + gamma
        let w_r_gamma: Vec<_> = w_r.par_iter().map(|w_r| w_r + gamma).collect();
        // Compute out_wire + gamma
        let w_o_gamma: Vec<_> = w_o.par_iter().map(|w_o| w_o + gamma).collect();
        // Compute fourth_wire + gamma
        let w_4_gamma: Vec<_> = w_4.par_iter().map(|w_4| w_4 + gamma).collect();
```

The length  of the upper witness vectors is indeed 21 instead of the padded one which would be `32`.

**Comment by CPerezz** [comment]
After making this ugly & quick solution:
```rust
pub(crate) fn compute_permutation_poly(
        &self,
        domain: &EvaluationDomain,
        w_l: &[Scalar],
        w_r: &[Scalar],
        w_o: &[Scalar],
        w_4: &[Scalar],
        (beta, gamma): &(Scalar, Scalar),
        (left_sigma_poly, right_sigma_poly, out_sigma_poly, fourth_sigma_poly): (
            &Polynomial,
            &Polynomial,
            &Polynomial,
            &Polynomial,
        ),
    ) -> Polynomial {
        let mut w_l_padded = vec![Scalar::zero(); domain.size()];
        let mut w_r_padded = vec![Scalar::zero(); domain.size()];
        let mut w_o_padded = vec![Scalar::zero(); domain.size()];
        let mut w_4_padded = vec![Scalar::zero(); domain.size()];
        let mut idx = 0usize;
        for coeff in &w_l[..] {
            w_l_padded[idx] = *coeff;
            idx += 1;
        }
        idx = 0;
        for coeff in &w_r[..] {
            w_r_padded[idx] = *coeff;
            idx += 1;
        }
        idx = 0;
        for coeff in &w_o[..] {
            w_o_padded[idx] = *coeff;
            idx += 1;
        }
        idx = 0;
        for coeff in &w_4[..] {
            w_4_padded[idx] = *coeff;
            idx += 1;
        }
        let z_evaluations = self.compute_fast_permutation_poly(
            domain,
            &w_l_padded,
            &w_r_padded,
            &w_o_padded,
            &w_4_padded,
            beta,
            gamma,
            (
                left_sigma_poly,
                right_sigma_poly,
                out_sigma_poly,
                fourth_sigma_poly,
            ),
        );
        Polynomial::from_coefficients_vec(domain.ifft(&z_evaluations))
    }
```

The `prove()` function is working now and it also passes the verification successfully.

Which basically means that we've completely  decoupled the `preprocessing` from the `composing` & `proving` stages.

Will code a more clean version of the solution & push it.

**Comment by CPerezz** [comment]
I also found why the `Proof` is not passing. 
But it's not related to this. So I'll open a new issue for it.
